### ISSUE TITLE
建议撤回 https://github.com/v2fly/v2ray-step-by-step/pull/118

### ISSUE THREAD

**Issue by ToutyRater** [v2fly/v2ray-step-by-step#127]
在 https://github.com/v2fly/v2ray-step-by-step/pull/118 中，为透明代理开启了 53 端口作为DNS 服务，我建议将此项修改撤回。原因在原文中的备注说过了：
> 在透明代理中，不要用 V2Ray 开放 53 端口做 DNS 服务器。如果这么做了，DNS 会出问题，这应该是个 BUG。

关于此问题，已经报告在 V2Ray 项目中 https://github.com/v2ray/v2ray-core/issues/1971 ，但至今未见修复，然而 https://github.com/v2fly/v2ray-step-by-step/pull/118 将此句提示删除。不知此问题的网友则可能会因 https://github.com/v2fly/v2ray-step-by-step/pull/118 修改的内容带来困扰。

**Comment by kslr** [comment]
cc @ilouiss
