### ISSUE TITLE
暫時移除多語言翻譯

### ISSUE THREAD

**Issue by dctxmei** [v2fly/v2ray-step-by-step#145]
@kslr 我查閱了目前的多語言翻譯狀況，可以說是非常糟糕了，在中文版本尚未修訂完成的情況下，我認為只需要保留 en_US 即可，待 zh_CN 和 en_US 都已完善，再著手多語言翻譯也不遲。

**Comment by kslr** [comment]
是的，甚至我认为只保留中文就可以了
