### ISSUE TITLE
將 VuePress 替換為 GitBook

### ISSUE THREAD

**Issue by dctxmei** [v2fly/v2ray-step-by-step#146]
@kslr 我反覆看了目前的 [.vuepress](https://github.com/v2fly/v2ray-step-by-step/tree/dev/.vuepress) 結構，尤其是其中的 [config.js](https://github.com/v2fly/v2ray-step-by-step/blob/dev/.vuepress/config.js)，我認為這不利於後續維護，對於不瞭解的人，很容易造成文章內容和左側目錄脫節。

gitbook-cli 工具雖然早已停止開發，但勝在可讓後繼的維護者專心於文章內容，其對於目錄的管理形式也比 vuepress 工具更為直觀，而無需再關心其它問題。

**Comment by kslr** [comment]
这个问题可以通过添加指引解决并且vuepress是支持自动菜单的，只是好像没有用，gitbook已经荒废好多年了

**Comment by dctxmei** [comment]
> 这个问题可以通过添加指引解决并且vuepress是支持自动菜单的，只是没有用，gitbook已经荒废好多年了

那就沒有問題了，我將關閉這個 Issue。
