### ISSUE TITLE
简易nignx分流 请求在高级中另开页面

### ISSUE THREAD

**Issue by inevity** [v2fly/v2ray-step-by-step#166]
https://gist.github.com/inevity/18dde844ddf14ed561905210999d57cb
基于协议数据的统一的代理分流工具。nignx作为前端，tls终止并基于tls承载的数据进行分流。简单易安装,仅仅添加21行代码。简化了V官方的TCP+TLS+WEB方案，替换了TCP+TLS分流器，也可以分流到trojan。

所以应该另开一页面。

**Comment by nicholascw** [comment]
merged in #165
