### ISSUE TITLE
TCP + TLS 分流器修改 V2Ray 的 systemd 配置文件的问题

### ISSUE THREAD

**Issue by kakaruoterl** [v2fly/v2ray-step-by-step#169]
ExecStartPre=/usr/bin/mkdir -p /tmp/v2ray-ds
ExecStartPre=/usr/bin/rm -rf /tmp/v2ray-ds/*.sock
ExecStartPost=/usr/bin/sleep 1
ExecStartPost=/usr/bin/chmod 777 /tmp/v2ray-ds/v2ray.sock
这4个部分并不适用所有系统，在ubuntu16.4系统中4条命令的位置为/bin，所以应修改为
ExecStartPre=/bin/mkdir -p /tmp/v2ray-ds
ExecStartPre=/bin/rm -rf /tmp/v2ray-ds/*.sock
ExecStartPost=/bin/sleep 1
ExecStartPost=/bin/chmod 777 /tmp/v2ray-ds/v2ray.sock
其它系统并未做测试

**Comment by kslr** [comment]
ubuntu 16太古老了，不考虑

**Comment by kakaruoterl** [comment]
> ubuntu 16太古老了，不考虑
看了你的回复我特地去测试了一下，ubuntu 18和debian10也这样，这是各大服务商centos外的主流系统了吧？
