### ISSUE TITLE
[feature]树莓派透明旁路由一键安装和Web管理界面

### ISSUE THREAD

**Issue by twotreeszf** [v2fly/v2ray-step-by-step#180]
Hello，根据透明旁路由相关文章，目前已经实现了一个简洁友好的管理页面，可支持一键安装：
https://github.com/twotreeszf/V2ray.Fun

**Comment by kslr** [comment]
只需要设置网关吗

**Comment by twotreeszf** [comment]
是的，我自测没问题了，只需要设置好网关，支持直连\分流\全局 三种模式，并能自动管理订阅

**Comment by twotreeszf** [comment]
帮忙删一下吧，换了地址哈

**Comment by iochen** [comment]
> 帮忙删一下吧，换了地址哈

You can just edit it.
