### ISSUE TITLE
推荐脚本已更换但是白话文教程里写的还是旧 go.sh，是否需要更新一下内容

### ISSUE THREAD

**Issue by lacafjh** [v2fly/v2ray-step-by-step#186]
## 关联或新增的页面 / related page
[下载安装 | V2Fly.org](https://www.v2fly.org/guide/install.html#linux-%E5%AE%89%E8%A3%85%E8%84%9A%E6%9C%AC)

## 描述 / description of the feature
[新脚本 fhs-install-v2ray](https://github.com/v2fly/fhs-install-v2ray)

**Comment by kslr** [comment]
看起来是的

静海闲人 <notifications@github.com> 于2020年8月10日周一 下午5:10写道：

**Comment by MuenYu** [comment]
#187 
在做了，在做了

**Comment by shijiantian** [comment]
才看到安装脚本变了，使用旧的脚本go.sh更新最新版的程序会导致无法连接，找了半天没发现问题，看到你这issue才知道脚本变了，程序的默认配置文件路径等都变了，换了新脚本重新安装并迁移配置文件才搞好。
