### ISSUE TITLE
[feature]希望增加新页面用于描述旧版脚本到新版脚本的迁移

### ISSUE THREAD

**Issue by MuenYu** [v2fly/v2ray-step-by-step#188]
## 关联或新增的页面 / related page
[install.md](../blob/transifex/zh_CN/install.md)
尚未添加：[migration.md](../blob/transifex/zh_CN/migration.md)

## 描述 / description of the feature
#186 目前正在着手于编写关于新脚本的安装教程
发现单页内容过多，希望增加一个页面用于专门描述旧版脚本到新脚本的迁移内容。

**Comment by kslr** [comment]
前段时间在 v2fly.org/ 文档中删除了，我建议如果要加的话写到文档哪里。

白话文的话可以适当向 文档转移，减少维护精力

**Comment by MuenYu** [comment]
👌
