### ISSUE TITLE
Docker deployment document optimization

### ISSUE THREAD

**Issue by whg517** [v2fly/v2ray-step-by-step#200]
## related page

https://github.com/v2fly/v2ray-step-by-step/blob/transifex/zh_CN/app/docker-deploy-v2ray.md

## description of the feature

Docker deploy content using the official [Docker mirror](https://hub.docker.com/r/v2ray/official), but the mirror for a long time didn't update, and referenced in the mirror of the script now is not recommended.

I recommend that the community add a Dockerfile repository to synchronize with Dockerhub, its mirrored versions and scripts.

I am not quite clear about the compilation rules of this document, so if I have any questions, I hope relevant personnel can answer me:

- Do you accept my Suggestions and PR for this content?
- If I want to write this part of the document, do I modify it directly or open a page?
- Is it acceptable for the community to maintain a Dockerfile and a Dockerhub repository?

---

<details>
<summary>中文</summary>

## 关联或新增的页面

https://github.com/v2fly/v2ray-step-by-step/blob/transifex/zh_CN/app/docker-deploy-v2ray.md

## 描述

Docker 部署内容使用了官方 [Docker 镜像](https://hub.docker.com/r/v2ray/official) 但该镜像很久没有更新，而且该镜像中引用的脚本现在也不推荐使用了。

我建议社区增加一个 Dockerfile 仓库同步到 Dockerhub ，其镜像版本和脚本同步。

我暂时还不太清楚设计对该文档的编撰规则，所以有一下疑问，还望有关人员解答：

- 是否接受我对本内容的建议和PR？
- 如果我想编写该部分文档，是直接修改还是领开一个页面？
- 社区是否接受维护一个 Dockerfile 同时维护 Dockerhub 仓库？

</details>

**Comment by kslr** [comment]
1. yes
2. current
3. https://hub.docker.com/r/v2fly/v2fly-core

**Comment by whg517** [comment]
Hello @kslr , thank you for your reply. I will start to plan relevant work.

For Docker deployed documents, I will readjust the layout of the page content and refer to the link of the original version of the page at the beginning, and explain the source and reason. The subsequent content of the document will only use the community-maintained Docker image.

Document preliminary planning:

- Docker deployment
- Docker Compose deployment

If feasible, I will start the documentation work.

**Comment by kslr** [comment]
Ok, But you can write https://www.v2fly.org/guide/install.html#docker

**Comment by whg517** [comment]
thanks guys.
