### ISSUE TITLE
[bug] GitHub Actions for Vuepress builds are broken

### ISSUE THREAD

**Issue by ToutyRater** [v2fly/v2ray-step-by-step#203]
## 与 bug 有关的页面 / related page
[tcp_tls_shunt_proxy.md](../blob/transifex/zh_CN/advanced/tcp_tls_shunt_proxy.md)等

## bug 描述 / description of the bug
内容与网站上发布的不一致

## 复现步骤 / how we can reproduce
最近的提交https://github.com/v2fly/v2ray-step-by-step/commit/b8c2d73cebb41572e1991362c6521e33339dc65e ，与[发布页](https://guide.v2fly.org/advanced/tcp_tls_shunt_proxy.html)的不一样，是不是部署的脚本挂了，近期的提交都没更新上去

**Comment by nicholascw** [comment]
fixed by f261099a12b15302185f85924ac5be9ea6952f83 26e1164d7bf2aaa3dbab041df431201165ae2d7b.
