### ISSUE TITLE
[feature] 高级篇 TCP + TLS + Web 页面建议增加 Nginx 配置

### ISSUE THREAD

**Issue by ImAmelie** [v2fly/v2ray-step-by-step#217]
## 关联或新增的页面
[tcp_tls_web.md](../blob/transifex/zh_CN/advanced/tcp_tls_web.md)

## 描述
为了方便不使用`HaProxy`，只用`Nginx`的用户，请在 TCP + TLS + Web 页面填加 Nginx 的配置，谢谢

**Comment by kslr** [comment]
里面明明有的

**Comment by ImAmelie** [comment]
@kslr

```
server {
  listen 8080;
  server_name example.com;
  root /var/www/html;
}
```

里面只有这5行，可是这5行并无法实现 TCP + TLS + Web 的功能

**Comment by kslr** [comment]
你可能需要认真看下原理一节

**Comment by ImAmelie** [comment]
@kslr 

谢谢提醒，是我糊涂了
