### ISSUE TITLE
Nginx如何设置v2ray的h2反代

### ISSUE THREAD

**Issue by adamgonglj** [v2fly/v2ray-step-by-step#76]
自己使用Nginx按照h2配置做的设置，提示是找不到destination

2019/09/11 19:25:09 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/http: unexpected status403] > v2ray.com/core/common/retry: all retry attempts failed
2019/09/11 19:25:09 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/http: unexpected status403] > v2ray.com/core/common/retry: all retry attempts failed
2019/09/11 19:25:12 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/http: unexpected status403] > v2ray.com/core/common/retry: all retry attempts failed
2019/09/11 19:25:15 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/http: unexpected status403] > v2ray.com/core/common/retry: all retry attempts failed
2019/09/11 19:25:17 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/http: unexpected status403] > v2ray.com/core/common/retry: all retry attempts failed
2019/09/11 19:25:21 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/http: unexpected status403] > v2ray.com/core/common/retry: all retry attempts failed
2019/09/11 19:25:23 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/http: unexpected status403] > v2ray.com/core/common/retry: all retry attempts failed
2019/09/11 19:25:27 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/http: unexpected status403] > v2ray.com/core/common/retry: all retry attempts failed
2019/09/11 19:25:29 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/http: unexpected status403] > v2ray.com/core/common/retry: all retry attempts failed
2019/09/11 19:25:31 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/http: unexpected status403] > v2ray.com/core/common/retry: all retry attempts failed
2019/09/11 19:25:34 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/http: unexpected status403] > v2ray.com/core/common/retry: all retry attempts failed
2019/09/11 19:25:38 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/http: unexpected status403] > v2ray.com/core/common/retry: all retry attempts failed
2019/09/11 19:25:40 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/http: unexpected status403] > v2ray.com/core/common/retry: all retry attempts failed
2019/09/11 19:25:43 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/http: unexpected status403] > v2ray.com/core/common/retry: all retry attempts failed
2019/09/11 19:25:46 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/http: unexpected status403] > v2ray.com/core/common/retry: all retry attempts failed
2019/09/11 19:25:49 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/http: unexpected status403] > v2ray.com/core/common/retry: all retry attempts failed
2019/09/11 19:25:51 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/http: unexpected status403] > v2ray.com/core/common/retry: all retry attempts failed
2019/09/11 19:25:54 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/http: unexpected status403] > v2ray.com/core/common/retry: all retry attempts failed
2019/09/11 19:25:56 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/http: unexpected status403] > v2ray.com/core/common/retry: all retry attempts failed
2019/09/11 19:25:59 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/http: unexpected status403] > v2ray.com/core/common/retry: all retry attempts failed
2019/09/11 19:26:02 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/http: unexpected status403] > v2ray.com/core/common/retry: all retry attempts failed
2019/09/11 19:26:05 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/http: unexpected status403] > v2ray.com/core/common/retry: all retry attempts failed
2019/09/11 19:26:08 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/http: unexpected status403] > v2ray.com/core/common/retry: all retry attempts failed
2019/09/11 19:26:10 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/http: unexpected status403] > v2ray.com/core/common/retry: all retry attempts failed

**Comment by kslr** [comment]
unexpected status403

**Comment by adamgonglj** [comment]
这个要怎么解决呀，我检查过我的配置，完全正确的。

加了阿里云的CDN，CDN支持H2协议。

**Comment by kslr** [comment]
只有日志我只能根据日志给你意见
