### ISSUE TITLE
请问如何添加目录

### ISSUE THREAD

**Issue by ToutyRater** [v2fly/v2ray-step-by-step#82]
前些日子提交了一个另一种透明代理配置方法，但发现没有目录，也没找到目录文件，所以目录该怎么添加？

**Comment by nicholascw** [comment]
ref #79 
目录文件？只是多了 tproxy.md 吧？

**Comment by nicholascw** [comment]
如果时说sidebar没有文章链接，修了，GitHub似乎有缓存。

**Comment by nicholascw** [comment]
emmm先关掉了，如果不是说这个问题的话再开吧。
