### ISSUE TITLE
感谢大伙的贡献

### ISSUE THREAD

**Issue by ToutyRater** [v2fly/v2ray-step-by-step#9]
要翻译和修改什么都随意，分发授权之类的我也是无所谓的

**Comment by ToutyRater** [comment]
说一下原来白话文教程的一些问题，这些问题许多我早就知道，只是因为种种原因没有改。

1. sniffing。教程中给的配置文件基本上都开启了sniffing，但是这会导致 Tor 无法使用，要使用 Tor 就得关闭 sniffing
2. TLS 证书。教程中使用 acme.sh 签发 TLS 证书，但是我的示例中使用普通用户权限运行 acme.sh，好像会导致 acme.sh 自动使用 crontab renew 证书出现问题，其二是示例中是将证书密钥复制到了 /etc/v2ray 目录下，哪怕证书续期了，也不会自动复制到 V2Ray 目录下
3. Nginx 配置。有网友反馈 Nginx 中的 proxy_set_header 导致无法与 V2Ray 搭配使用；但是教程中给出的配置我在 2018 年春测试过是无问题的，我对 Nginx 基本上不懂，所以是不是后来的更新导致这个问题我也不知道，这一点需要大家确认修正
4. CDN。教程中说 HTTP/2 与 CDN 结合使用是我胡诌的，实际上不可行
5. 负载均衡 oubound tag 匹配。V2Ray 只需要匹配 tag 的前缀，而不是全字符串匹配，教程中没有说明
6. 路由功能。路由功能中有一节注意事项，有一些原来想写的东西没有写，就留了几个标题

除了上面这几点之外，我印象中还有其他问题的，一下子也没能全部想起来了，想起来再继续补充。因为个人原因我现在几乎没有动力继续维护白话文教程了，管理员说我是跑路了也没什么错。所以，我内心非常感谢有人接着维护教程，并翻译成其他语言版本。

**Comment by Jasonsec1** [comment]
nginx 关于WebSocket+TLS+Web反向代理配置，下面 
proxy_set_header Host $host; 和proxy_set_header Host $http_host;其实应该效果一样，但同时使用会导致失败，这里可以修改一下，删除一个亲测可用，听说都不要也可以，这个没测试过，

**Comment by nicholascw** [comment]
具体的其他问题就不要在这里回复了吧，另开新 issue 比较好。
